lab4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'lab4.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace='polls')),
]

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='details'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	
]

polls/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
import datetime
# Create your models here.

@python_2_unicode_compatible
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

@python_2_unicode_compatible
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.views import generic
# Create your views here.

class IndexView(generic.ListView):
	template_name = 'index.html'
	context_object_name = 'latest_question_list'
	def get_queryset(self):
		return Question.objects.order_by('-pub_date')[:5]
		
class DetailsView(generic.DetailView):
	model = Question
	template_name = 'details.html';

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'details.html', { 'question': question, 'error_message': "You did not select a choice!"})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/details.html
<html>
<body>
	<h1>{{ question.question_text }}</h1>
	{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}
	<form action="{% url 'polls:vote' question.id %}" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" value="{{ choice.id }}" />
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
			<br/>
		{% endfor %}
		<input type="submit" value="Vote!" />
	</form>
</body>
</html>

polls/templates/index.html
<html>
<body>
<h1> POLLS </h1>
{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
			<li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p> No Questions Available </p>
{% endif %}
</body>
</html>

polls/templates/results.html
<H1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.vote }} votes {{ choice.votes }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:details' question.id %}">Vote again?</a>